name: Agents IA – Test manuel
on:
  workflow_dispatch:
jobs:
  run-agents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Installer BeautifulSoup
        run: pip install beautifulsoup4
      - name: Exécuter tests QA
        run: python agents/agent_qa.py

